/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphmfsetusage;

import graph.Graph;
import graph.GraphExceptions;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 * Graphic explorer of the forest generated by the Kruskal Algorithm
 * @author daniel
 */
public class DrawTrees extends JFrame {

  private JTree tree;

  public TreeNode createTree(Graph<String, Double> graph, ArrayList<String> rootNodes) throws GraphExceptions {
    DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root");
    for (int i = 0; i < rootNodes.size(); i++) {

      DefaultMutableTreeNode treeRootNode = new DefaultMutableTreeNode(rootNodes.get(i));
      root.add(treeRootNode);

      Queue<DefaultMutableTreeNode> treeQueue = new LinkedList<DefaultMutableTreeNode>();
      treeQueue.add(treeRootNode);
      Set<String> checkedNodes = new HashSet<>();
      while (!treeQueue.isEmpty()) {

        DefaultMutableTreeNode parentTreeNode = treeQueue.poll();

        ArrayList<String> adjNodes = graph.getAdjNodes((String) parentTreeNode.getUserObject());
        for (int j = 0; j < adjNodes.size(); j++) {
          if (!checkedNodes.contains(adjNodes.get(j))) {
            DefaultMutableTreeNode childrenTreeNode = new DefaultMutableTreeNode(adjNodes.get(j));
            parentTreeNode.add(childrenTreeNode);
            treeQueue.add(childrenTreeNode);
            checkedNodes.add((String) parentTreeNode.getUserObject());
          }
        }
      }
    }
    return root;
  }

  public DrawTrees(Graph<String, Double> graph, ArrayList<String> rootNodes) throws GraphExceptions {

    TreeNode root = createTree(graph, rootNodes);
    tree = new JTree(root);
    add(tree);

    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.setTitle("JTree Example");
    this.pack();
    setSize(new Dimension(400, 300));
    this.setVisible(true);
  }
}
